{% set name = "napari-arboretum" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-arboretum-{{ version }}.tar.gz
  sha256: 9b1837bb02727edd045b7a341af29bd466aef3ae01bbc81141c71117cd5b6078

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - matplotlib-base
    - napari >=0.4.0
    - napari-matplotlib >=0.2.1
    - numpy >=1.17.3
    - pandas
    - pooch >=1
    - python >={{ python_min }}
    - qtpy
    - scikit-image
    - vispy

test:
  imports:
    - napari_arboretum
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-arboretum
  summary: Track graph and lineage tree visualization with napari
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/lowe-lab-ucl/arboretum

extra:
  recipe-maintainers:
    - quantumjot
    - goanpeca
    - jaimergp
